version: "3.9"
services:
  reactive_client:
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - "postgres"
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=persondb 

