curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
curl  http://localhost:8070/spring/greet/ &
