curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
curl  http://localhost:8080/vertx/greet/ &
