/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reactive;


import lombok.extern.log4j.Log4j;
import lombok.extern.log4j.Log4j2;

import java.io.IOException;
import java.util.Scanner;

@Log4j2
public class App {

    public static void main(String[] args) throws InterruptedException, IOException{

    }

}
