curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/ &
curl  http://localhost:8080/alternatives/thread/
