curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/ &
curl  http://localhost:8080/vertx/blocking/
